# Generated by Django 3.0.4 on 2020-03-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('ans1', models.CharField(max_length=2)),
                ('ans2', models.CharField(max_length=2)),
                ('ans3', models.CharField(max_length=2)),
                ('ans4', models.CharField(max_length=2)),
                ('ans5', models.CharField(max_length=2)),
                ('feedback', models.CharField(max_length=200)),
            ],
        ),
    ]
